version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/"
      - "/requirements"
    schedule:
      interval: weekly
    groups:
      cross-directory-dependencies:
        group-by: dependency-name
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
